name: Release

concurrency: ci-${{ github.ref }}

on:
  workflow_dispatch:
  
  push:
    branches: [ main ] # Default release branch
    paths-ignore:
      - '.github/**'
      - 'docs/**'
      - '**/.ts/**'
      - '**/.nx/**'

env:
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
  DOTNET_CLI_TELEMETRY_OPTOUT: true

jobs:
  call-workflow-nuget-release:
    uses: Digitalroot-Valheim/.github/.github/workflows/nuget.release.yml@main
    secrets:
      aws-access-key-id: ${{ secrets.NUGET_S3_REPO_KEY_ID }}
      aws-secret-access-key: ${{ secrets.NUGET_S3_REPO_KEY_SECRET }}
      nexus-api-key: ${{ secrets.NEXUS_API_KEY }}
      nexus-cookie-nxid-header: ${{ secrets.NEXUS_COOKIE_HEADER_NEXUSID }}
      nexus-cookie-sid-header: ${{ secrets.NEXUS_COOKIE_HEADER_SID_DEVELOP }}
      ts-api-key: ${{ secrets.TS_SERVICEACCOUNT }}
      webhook_url: ${{ secrets.VALHEIM_DISCORD_TITANS_WEBHOOK_URL }}

    with:
      sln-file-name: Digitalroot.Valheim.GoldBars
      proj-file-name: Digitalroot.Valheim.GoldBars
      is-nuget-package: false
      nexus-enable-upload: true
      nexus-mod-id: 1448
      ts-enable-upload: true
      ts-name: Digitalroots_GoldBars
      ts-description: "Adds gold bars that are craftable from coins. A placed Coin Pile adds one comfort. A placed Gold Stack adds two comfort. Gold bars can be turned back into coins at the forge."
      ts-categories: "client-side server-side crafting" #https://thunderstore.io/api/experimental/community/valheim/category/
      ts-dependencies: ValheimModding-Jotunn-2.20.0
